let s1i = document.getElementById('s1i');
let s1p = document.getElementById('s1p');
let s1c = document.getElementById('s1c');
let s2i = document.getElementById('s2i');
let s2p = document.getElementById('s2p');
let s2c = document.getElementById('s2c');
let s3i = document.getElementById('s3i');
let s3p = document.getElementById('s3p');
let s3c = document.getElementById('s3c');
let s4i = document.getElementById('s4i');
let s4p = document.getElementById('s4p');
let s4c = document.getElementById('s4c');
let sp1i = document.getElementById('sp1i');
let sp1p = document.getElementById('sp1p');
let sp1c = document.getElementById('sp1c');
let sp2i = document.getElementById('sp2i');
let sp2p = document.getElementById('sp2p');
let sp2c = document.getElementById('sp2c');
let sp3i = document.getElementById('sp3i');
let sp3p = document.getElementById('sp3p');
let sp3c = document.getElementById('sp3c');
let sp4i = document.getElementById('sp4i');
let sp4p = document.getElementById('sp4p');
let sp4c = document.getElementById('sp4c');
let pa1i = document.getElementById('pa1i');
let pa1p = document.getElementById('pa1p');
let pa1c = document.getElementById('pa1c');
let pa2i = document.getElementById('pa2i');
let pa2p = document.getElementById('pa2p');
let pa2c = document.getElementById('pa2c');
let pa3i = document.getElementById('pa3i');
let pa3p = document.getElementById('pa3p');
let pa3c = document.getElementById('pa3c');
let pa4i = document.getElementById('pa4i');
let pa4p = document.getElementById('pa4p');
let pa4c = document.getElementById('pa4c');
let background = document.getElementById('platbg');
let saladestext = document.getElementById('saladestext');
let spetext = document.getElementById('spetext');
let spe = document.getElementById('spe');
let patestext = document.getElementById('patestext');
let pates = document.getElementById('pates');
let salades = document.getElementById('salades');
let hamburgercarousel = document.getElementById('hamburgercarousel');
let plat = document.getElementById('plat');
let platcol = document.getElementById('platcol');
let formplat = document.getElementById('formplat');
document.getElementById('lienplat');
document.getElementById('descriptionplat');
var platImage, platDesc;

function Commande(lien, description) {
        lienplat.src = lien;
        descriptionplat.innerHTML = description;
}
s1c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    saladestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = s1i.src;
    platDesc = s1p.innerHTML;
    Commande(platImage, platDesc);
});
s2c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    saladestext.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = s2i.src;
    platDesc = s2p.innerHTML;
    Commande(platImage, platDesc);
});
s3c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    saladestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = s3i.src;
    platDesc = s3p.innerHTML;
    Commande(platImage, platDesc);
});
s4c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    saladestext.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = s4i.src;
    platDesc = s4p.innerHTML;
    Commande(platImage, platDesc);
});

sp1c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    saladestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = sp1i.src;
    platDesc = sp1p.innerHTML;
    Commande(platImage, platDesc);
});
sp2c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    saladestext.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = sp2i.src;
    platDesc = sp2p.innerHTML;
    Commande(platImage, platDesc);
});
sp3c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    saladestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = sp3i.src;
    platDesc = sp3p.innerHTML;
    Commande(platImage, platDesc);
});
sp4c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    saladestext.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = sp4i.src;
    platDesc = sp4p.innerHTML;
    Commande(platImage, platDesc);
})
pa1c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    saladestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = pa1i.src;
    platDesc = pa1p.innerHTML;
    Commande(platImage, platDesc);
});
pa2c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    saladestext.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = pa2i.src;
    platDesc = pa2p.innerHTML;
    Commande(platImage, platDesc);
});
pa3c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    saladestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = pa3i.src;
    platDesc = pa3p.innerHTML;
    Commande(platImage, platDesc);
});
pa4c.addEventListener('click', (e) => {
    background.style.display = 'none';
    salades.style.display = 'none';
    hamburgercarousel.style.display = 'none';
    saladestext.style.display = 'none';
    spe.style.display = 'none';
    spetext.style.display = 'none';
    pates.style.display = 'none';
    patestext.style.display = 'none';
    formplat.style.display = 'flex';
    plat.style.display = 'flex';
    platcol.style.display = 'flex';
    platImage = pa4i.src;
    platDesc = pa4p.innerHTML;
    Commande(platImage, platDesc);
})